name = "moe-counter"
main = "dist/worker.js"
compatibility_date = "2024-02-27"
workers_dev = false

[[routes]]
pattern = "moe.counter.weidows.tech"
custom_domain = true

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "moe-counter"
database_id = "00b1f08c-2fba-402d-80f3-7debf4b3938e"
